package Monopoly_Properties;

/**
 * Relationships between Position and the Space
 * @author Jonathan Dang
 *
 */
public enum Position_Relationships {
	GO(0),
	MEDITERANEAN_AVENUE(1),
	COMMUNITY_CHEST1(2),
	BALTIC_AVENUE(3),
	INCOME_TAX(4),
	READING_RAILROAD(5),
	ORIENTAL_AVENUE(6),
	CHANCE_PURPLE(7),
	VERMONT_AVENUE(8),
	CONNECTICUT_AVENUE(9),
	JAIL(10),
	SAINT_CHARLES_PLACE(11),
	ELECTRIC_COMPANY(12),
	STATES_AVENUE(13),
	VIRGINIA_AVENUE(14),
	PENNSYLVANIA_RAILROAD(15),
	SAINT_JAMES_PLACE(16),
	COMMUNITY_CHEST2(17),
	TENNESSEE_AVENUE(18),
	NEW_YORK_AVENUE(19),
	FREE_PARKING(20),
	KENTUCKY_AVENUE(21),
	CHANCE_BLUE(22),
	INDIANA_AVENUE(23),
	ILLINOISE_AVENUE(24),
	BBQ_RAILROAD(25),
	ATLANTIC_AVENUE(26),
	VENTOR_AVENUE(27),
	WATER_WORKS(28),
	MARVIN_GARDENS(29),
	GO_TO_JAIL(30),
	PACIFIC_AVENUE(31),
	NORTH_CAROLINA_AVENUE(32),
	COMMUNITY_CHEST3(33),
	PENNSYLVANIA_AVENUE(34),
	SHORT_LINE(35),
	CHANCE_ORANGE(36),
	PARK_PLACE(37),
	LUXURY_TAX(38),
	BOARDWALK(39);

	Position_Relationships(int i) {
		this._value = i;
	}
	
	private int _value;
	
	public int getLocation()
	{
		return _value;
	}
}
